### ISSUE TITLE
No module named 'caper.caper_uri'

### ISSUE THREAD

**Issue by qisun2** [ENCODE-DCC/qc2tsv#1]
qc2tsv does not work with new release of caper, as caper.caper_uri is obsolete now. 

File "/programs/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/qc2tsv/qc2tsv.py", line 13, in <module>
    from caper.caper_uri import init_caper_uri, CaperURI
ModuleNotFoundError: No module named 'caper.caper_uri'

**Comment by leepc12** [comment]
Fixed. `pip install qc2tsv==0.1.3`
